services:

  mysql:
    image: mysql:8.0
    container_name: projeto_integrador_mysql
    restart: unless-stopped

    env_file:
      - .env
    
    enviroment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports: 
      - "3316:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -pMYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 25s
  backend:
    build:
      context: ./backend
    container_name: projeto_integrador_backend
    restart: unless-stopped

    env_file:
     - .env
    
    depends_on:
      mysql:
        condition: service_healthy
    
    enviroment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_DEBUG: ${FLASK_DEBUG}
    
    ports: 
      - "5000:5000"
    
    volumes:
      - ./backend:/app

volumes:
  mysql_data: